name: 'Github automated releases'
author: 'Vincent Payeur'
description: 'Used to put labels on pull requests.'

runs:
  using: 'composite'
  steps:
    - name: Get config file
      uses: VincePayeur/CompositeAction/.github/actions/Commit-ReleaseDrafter-Config@main

    - name: Label pull request
      uses: release-drafter/release-drafter@v5
      with:
        disable-releaser: true
        disable-autolabeler: false