name: 'Get Release-Drafter config file'
author: 'Vincent Payeur'
description: 'Used to commit config release-drafter config file in the repo.'

runs:
  using: 'composite'
  steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        path: ./action

    - name: Checkout config repo
      uses: actions/checkout@v3
      with:
        repository: VincePayeur/CompositeAction
        path: ./config

    - name: Commit and push config file
      shell: bash
      run: |
        mkdir -p action/.github
        cp config/.github/release-drafter.yml action/.github/
        cd action/
        git config --global user.name "Github action BOT"
        git config --global user.email "BOT@users.noreply.github.com"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -am "Automated commit to add/modify release-drafter.yml config file"
        git push