name: 'Github automated releases'
author: 'Vincent Payeur'
description: 'Used to create automated releases with pushes to the default branch.'

runs:
  using: 'composite'
  steps:
    - name: Get config file
      uses: VincePayeur/CompositeAction/.github/actions/Commit-ReleaseDrafter-Config@main

    - name: Get new release tag name
      id: release_name
      uses: release-drafter/release-drafter@v5
      with:
        disable-releaser: false
        disable-autolabeler: true

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Update galaxy.yml with the new release version
      shell: bash
      run: |
        git pull
        version="${{ steps.release_name.outputs.name }}"
        sed -i 's/[1-9]\?[0-9]\.[1-9]\?[0-9]\.[1-9]\?[0-9]/'"${version:1}"'/' galaxy.yml

    - name: Commit and push changes to galaxy.yml
      shell: bash
      run: |
        git config --global user.name "Github action BOT"
        git config --global user.email "BOT@users.noreply.github.com"
        git diff --quiet && git diff --staged --quiet || git commit -am "Automated commit to update galaxy.yml"
        git push

    - name: Create new release
      uses: release-drafter/release-drafter@v5
      with:
        publish: true
        disable-releaser: false
        disable-autolabeler: true