name: 'Github automated releases'
author: 'Vincent Payeur'
description: 'Used to create automated releases.'

runs:
  using: 'composite'
  steps:
    - name: Get config file
      uses: VincePayeur/CompositeAction/.github/actions/Commit-ReleaseDrafter-Config@main

    - name: Create new release
      uses: release-drafter/release-drafter@v5
      with:
        publish: true
        disable-releaser: false
        disable-autolabeler: true