name: 'Github automated releases'
author: 'Vincent Payeur'
description: 'Used to create automated releases with pushes to the default branch.'

runs:
  using: 'composite'
  steps:
    - name: Create new release
      uses: release-drafter/release-drafter@v5
      with:
        publish: true
        disable-releaser: false
        disable-autolabeler: true