name: Release Drafter
on:
  workflow_call:
    inputs:
      is_collection:
        type: boolean
        required: false
        default: false
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions:
  contents: write
  pull-requests: write

jobs:
  Release_Drafter_Labeler:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Label pull request
        uses: VincePayeur/CompositeAction/.github/actions/Labeler@main

  Release_Draft:
    if: github.event_name == 'push' && !inputs.is_collection
    runs-on: ubuntu-latest
    steps:
      - name: Create new release
        uses: VincePayeur/CompositeAction/.github/actions/Default-Release@main

  Release_Draft_Collection:
    if: github.event_name == 'push' && inputs.is_collection
    runs-on: ubuntu-latest
    steps:
      - name: Create new release
        uses: VincePayeur/CompositeAction/.github/actions/Collection-Release@main